# Generated by Django 5.2.7 on 2025-10-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedString',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('length', models.IntegerField()),
                ('is_palindrome', models.BooleanField()),
                ('unique_characters', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('sha_256_hash', models.CharField(max_length=64, unique=True)),
                ('character_frequency_map', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analyzed string',
                'verbose_name_plural': 'Analyzed strings',
                'ordering': ['-created_at'],
            },
        ),
    ]
